version: '3'
services:
  # MySQL
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  # Rails
  app:
    build:
      context: ./
      dockerfile: ./infra/dockerfiles/rails/Dockerfile
    volumes:
      - ./backend:/myapp
    ports:
      - "5000:3000"
    links:
      - db
      - search
    tty: true
    stdin_open: true

  # Elasticsearch
  search:
    build:
      context: ./
      dockerfile: ./infra/dockerfiles/search/Dockerfile
    environment:
      - cluster.name=rails-sample-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./search_data:/usr/share/elasticsearch/data

  # 必要なときだけ
  # kibana
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:6.7.2
  #   environment:
  #     SERVER_NAME: localhost:5601
  #     ELASTICSEARCH_URL: http://localhost:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - search
